<a href="https://colab.research.google.com/github/Vishalkumar800/Titanic-Dataset-Cleaning-and-EDA-/blob/main/complete_titanic_model_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [377]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [378]:
data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [379]:
data_df = data.copy()
data_test = data.copy()

In [380]:
data_test.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [381]:
# axis  = 0 rows
# axis = 1 column
data_df.drop(["Cabin"] , axis = 1,  inplace = True )
data_test.drop(["Cabin"] , inplace= True , axis= 1)

```
In test.csv one column is missing that is survived column because that is test column.

```

```
Survived : 0 (Not Survived ) and 1 means alive
PClass : means which class passenger is in like 1(first class ), 2 (secondclass) , 3 (thirdclass)

SibSp : Siblings + Spouses
```
Siblings means brother or sister where as spouses husband/wife.

```
Parch : Parent + Childern
Fare : Price of ticket

```

 `Embarked`  You can call station name
  | Code | Port        |
 | ----  | ----------- |
| `C`   | Cherbourg   |
| `Q`   | Queenstown  |
| `S`   | Southampton |

`Numerical` : Age , Fare

`Categorical`  : Categorical , PClass , Survived , Sex , SibSp , Parch , Embarked

`Mixed` : Name , Ticket

In [382]:
# function is used to perform an action or operation . In hindi function se kaam aap kuch karwate ho
# attributes : An attribute is a property or piece of information associated with an object. It tells us what the object has or what it is like.
### where as attributes se information lete ho.

data_df.info() , data_df.shape # shape is attributes means

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

(None, (891, 11))

In [383]:
data_df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

## Problems in these dataset

```
Name : I need to split the original `Name` column into two separate columns: `NameOnly` , title and `Surname`.

Age : Age has so missing values so I need to handle it .

Fare : Fair column contains whole family ticket price example if a family hai 4 members then fair contain whole ticket price of family

SibSp + Parch combine these two columns and create a new column that is family size.

so i need to find single member ticket price.

Embarked = Two missing values.

```

In [384]:
data_df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C

In [385]:
data_df["SurName"] = data_df["Name"].str.split(",").str[0]

In [386]:
data_df["NameOnly"] = data_df["Name"].str.split(",").str[1]

In [387]:
data_df["title"] = data_df["NameOnly"].str.split(".").str[0]

In [388]:
data_df["Name_Single"] = data_df["NameOnly"].str.split(".").str[1]

In [389]:
data_df.drop(["NameOnly"] , axis=1 , inplace=True)

In [390]:
data_df["family"] = data_df["SibSp"] + data_df["Parch"] +1

In [391]:
data_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,SurName,title,Name_Single,family
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,Braund,Mr,Owen Harris,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Heikkinen,Miss,Laina,1

In [392]:
data_df.drop(["SibSp" , "Parch"], axis = 1, inplace = True)

In [393]:
data_df["family"].value_counts()

family
1     537
2     161
3     102
4      29
6      22
5      15
7      12
11      7
8       6
Name: count, dtype: int64

In [394]:
def family_size(n):
  if n ==1 :
    return "alone"
  elif n > 1 and n < 5 :
    return "small"
  else:
    return "large"

In [395]:
data_df["family_type"] = data_df["family"].apply(family_size)

In [396]:
data_df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Embarked,SurName,title,Name_Single,family,family_type
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,S,Braund,Mr,Owen Harris,2,small
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),2,small

In [397]:
data_df["family"].value_counts()

family
1     537
2     161
3     102
4      29
6      22
5      15
7      12
11      7
8       6
Name: count, dtype: int64

In [398]:
data_df[data_df["family"] == 8 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Embarked,SurName,title,Name_Single,family,family_type
59,60,0,3,"Goodwin, Master. William Frederick",male,11.0,CA 2144,46.9,S,Goodwin,Master,William Frederick,8,large
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.0,CA 2144,46.9,S,Goodwin,Miss,Lillian Amy,8,large
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.0,CA 2144,46.9,S,Goodwin,Master,Sidney Leonard,8,large
480,481,0,3,"Goodwin, Master. Harold Victor",male,9.0,CA 2144,46.9,S,Goodwin,Master,Harold Victor,8,large
678,679,0,3,"Goodwin, Mrs. Frederick (Augusta Tyler)",female,43.0,CA 2144,46.9,S,Goodwin,Mrs,Frederick (Augusta Tyler),8,large
683,684,0,3,"Goodwin, Mr. Charles Edward",male,14.0,CA 2144,46.9,S,Goodwin,Mr,Charles Edward,8,large

In [399]:
data_df["individualFare"] = data_df["Fare"] / data_df["family"]

In [400]:
data_df.drop("Fare", axis = 1 , inplace=True)

In [401]:
data_df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Embarked,SurName,title,Name_Single,family,family_type,individualFare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,S,Braund,Mr,Owen Harris,2,small,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,C,Cumings,Mrs,John Bradley (Florence Briggs Thayer),2,small,35.64165

In [402]:
data_df["title"].value_counts()

title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [403]:
print(data_df["title"].unique())

[' Mr' ' Mrs' ' Miss' ' Master' ' Don' ' Rev' ' Dr' ' Mme' ' Ms' ' Major'
 ' Lady' ' Sir' ' Mlle' ' Col' ' Capt' ' the Countess' ' Jonkheer']

In [404]:
mr = ["Mr", "Col", "Major", "Don", "Sir", "Capt", "Dr", "Rev", "Jonkheer" , "Master"]

miss = ["Miss", "Mrs", "Ms", "Mlle", "Mme", "Lady", "the Countess"]

def titleFunc(title):
  title = title.strip()
  if title in mr:
    return "Mr"
  elif title in miss:
    return "Miss"
  else:
    return "Other"

In [405]:
data_df["title"] = data_df["title"].apply(titleFunc)

In [406]:
data_df["title"].value_counts()

title
Mr      578
Miss    313
Name: count, dtype: int64